[tool.poetry]
name = "your-app-name"
version = "0.1.0"
description = ""
authors = ["Your Name <email@example.com>"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
sentence-transformers= ">=5.1.1,<6.0.0"
spacy = ">=3.8.7,<4.0.0"
fastapi = ">=0.117.1,<0.118.0"
uvicorn = ">=0.37.0,<0.38.0"
pydantic = ">=2.11.9,<3.0.0"
punq = ">=0.7.0,<0.8.0"
dotenv = ">=0.9.9,<0.10.0"
polars = ">=1.33.1,<2.0.0"
catboost = ">=1.2.8,<2.0.0"



[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
