services:
  nest:
    image: node:latest
    ports:
      - '3000:3000'
    volumes:
      - ../:/lct-adera-2025/ # было ../../:/monorepo/
    working_dir: /lct-adera-2025/ # было /monorepo/
    entrypoint: bash -c "yarn c:start"
    env_file: ../packages/backend/adera-core/.env
    networks:
      - backend_net

  # MinIO
  minio:
    image: minio/minio:latest
    ports:
      - ${MINIO_BIND}:9000
      - ${MINIO_CONSOLE_BIND}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - backend_net

volumes:
  postgres_data:
  minio_data:

networks:
  backend_net:
    name: backend_net
    driver: bridge
