services:
  postgres:
    image: postgres:16
    ports:
      - ${POSTGRES_BIND}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - adera_backend_net

  # MinIO
  minio:
    image: minio/minio:latest
    ports:
      - ${MINIO_BIND}:9000
      - ${MINIO_CONSOLE_BIND}:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  postgres_data:
  minio_data:

networks:
  adera_backend_net:
    name: adera_backend_net
    driver: bridge
    # external: true
